; custom-php.ini

; Define o número máximo de variáveis de entrada permitidas
max_input_vars = 5000
upload_max_filesize = 4G
post_max_size = 4G
max_execution_time = 900
memory_limit = 4G
max_input_time = 900
default_socket_timeout = 600
